### ISSUE TITLE
Making PXE boot configuration optional

### ISSUE THREAD

**Issue by tmasteli** [dalmatialab/tftp#1]
Directory `/var/lib/tftpboot` should be empty by default so this image can be used as a regular TFTP server, not necessarily PXE boot. 
Moreover, an environment variable `PXEBOOT` should be added with possible values `true/false`, with `false` being the default.
Finally, a script should be added as an entrypoint that checks if `PXEBOOT` variable is `true` and if `/var/lib/tftpboot` or some of its PXE configuration subdirectories are empty; if so it should copy PXE boot configuration into it.

This would also solve an issue when mounting `/var/lib/tftpboot` directory from a host, being initially empty on the mount; above suggestion would copy the default configuration into `/var/lib/tftpboot` directory so a user has something to start with.

**Comment by dbazina-dev** [comment]
This was fixed in Commit 168a0f3cbc297f225fdeed72a3c76fc611c17513.
Server can be run as TFTP server with or without PXE BOOT configuration, environment variable PXEBOOT was declared for this purpouse.
