### ISSUE TITLE
Custom parameters for TFTP server

### ISSUE THREAD

**Issue by tmasteli** [dalmatialab/tftp#2]
Make `/usr/sbin/in.tftpd` an ENTRYPOINT and `-v -L --secure /var/lib/tftpboot` a CMD, so a user can provide custom input parameters without overriding the ENTRYPOINT.
In a combination with a bash script as an ENTRYPOINT, similar thing can be done by running `/usr/sbin/in.tftpd` at the end of the script and taking input parameters from CMD.

**Comment by dbazina-dev** [comment]
This was fixed in commit 168a0f3cbc297f225fdeed72a3c76fc611c17513.
User can change TFTP parameters by overriding default ones, this is done by adding parameters at the end of docker run command.
